name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build/Pack
      run: msbuild Vortice.sln -t:restore,build,pack /p:Configuration=Release /p:SymbolPackageFormat=snupkg /p:Packing=true

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: artifacts\*.nupkg
        if-no-files-found: error

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: |      
          if ( "${{github.ref}}" -match "^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$" ) {
              dotnet nuget push packages/**/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate --source https://api.nuget.org/v3/index.json
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
      working-directory: .
